### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by LordAldaron** [scorefall/scorefall-studio#3]
## Roadmap to first stable iteration (0.1.0)
- [ ] [sfstudio-web](https://github.com/scorefall/scorefall-studio/tree/master/sfstudio-web) the actual program (putting everything together).
  - [x] Start building WASM application in Rust for [scorefall-studio](https://github.com/scorefall/scorefall-studio).
    - [ ] Design 2-mode keyboard Input, and touchscreen/mouse interface
    - [ ] Implement input.
  - [ ] [scof](https://github.com/scorefall/scorefall-studio/tree/master/scof) structs of musical notation.
    - [x] Add score metadata struct
    - [x] Add instrument & note structs
    - [ ] Scof Parser with Muon
      - [x] Muon Specification
      - [x] Muon Parser
      - [ ] Zip File support
  - [ ] [muflor](https://github.com/scorefall/scorefall-studio/tree/master/muflor) music scores in [scof](https://github.com/scorefall/scof) structs into SVG files.
    - [x] Convert Bravura font into SVG defs.
    - [x] Rendering.
    - [x] Depends on `scof` for music structs.
    - [x] API to take `scof` music structs and render it.
    - [ ] Be able to render all supported glyphs.
      - [ ] Beaming
      - [ ] Clefs
      - [ ] Time Signatures
      - [ ] Articulations
      - [ ] Dynamics
      - [ ] Tempo changes
      - [ ] Lyrics
      - [ ] Rehearsal Markings
      - [ ] Ledger Lines
  - [ ] [scorefall-studio](https://github.com/scorefall/scorefall-studio/tree/master/scorefall-studio)
    - [ ] Functions for editing score.
      - [x] Durations
      - [ ] Pitches
        - [x] Basic pitch manipulation
        - [ ] Key Signatures
        - [ ] Flats & Sharps
        - [ ] Quarter Tones
  - [ ] [musicxml](https://github.com/scorefall/musicxml) parser with [quick-xml](https://crates.io/crates/quick-xml).
    - [ ] Translation to Scof
      - [ ] Score metadata iterator
      - [ ] Instrument & Notes iterators
